### ISSUE TITLE
Python toolkit from pypi fails to run: 'verovio._verovio' has no attribute 'toolkit_swiginit'

### ISSUE THREAD

**Issue by earboxer** [rism-digital/verovio#2204]
After I `pip3 install verovio` (x86_64 linux), I can't create a toolkit.
(I have swig 3.0.12-2 on debian buster)

```
# python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import verovio
>>> vrvrToolkit = verovio.toolkit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/verovio/verovio.py", line 93, in __init__
    _verovio.toolkit_swiginit(self, _verovio.new_toolkit(initFont))
AttributeError: module 'verovio._verovio' has no attribute 'toolkit_swiginit'
```

But it works fine if I [build the toolkit](https://book.verovio.org/installing-or-building-from-sources/python.html#building-the-toolkit) from source.

**Comment by earboxer** [comment]
If I upgrade to swig 4.0 (after switching /etc/apt/sources.list to bullseye), then the one installed through pip will work.
