### ISSUE TITLE
Crash when rendering mei 2013 mensural notation

### ISSUE THREAD

**Issue by alastair** [rism-digital/verovio#2425]
**Describe the problem**
On recent versions of verovio, I get a crash when rendering the attached MEI file (generated by aruspix, mei v2013)
Notably, I have an [old js version of verovio](https://github.com/TransformingMusicology/f-tempo/blob/master/static/ext/verovio-toolkit.js) (i'm not sure exactly which version it is) which renders this file without problems: 

**To Reproduce**
running: `./verovio -r ../data/ -o output.svg ../GB-Lbl_A103b_025_0.mei`

**Expected behavior**
file renders to SVG

**Input data**
The smallest example (MEI unless about another input format) to reproduce the problem
[GB-Lbl_A103b_025_0.mei.txt](https://github.com/rism-digital/verovio/files/7345499/GB-Lbl_A103b_025_0.mei.txt)

**Verovio information**
 - Version of Verovio: github `develop` branch

**Environment information (as appropriate)**
 - OS: linux

**Additional context**
stacktrace

```
verovio: /home/alastair/verovio/src/doc.cpp:1836: vrv::Score* vrv::Doc::GetCurrentScore(): Assertion `m_currentScore' failed.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348273280) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(gdb) where
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348273280) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737348273280) at pthread_kill.c:80
#2  __GI___pthread_kill (threadid=140737348273280, signo=signo@entry=6) at pthread_kill.c:91
#3  0x00007ffff7aaf476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7a957b7 in __GI_abort () at abort.c:79
#5  0x00007ffff7a956db in __assert_fail_base (
    fmt=0x7ffff7c49770 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x555555e44218 "m_currentScore", file=0x555555e437b8 "/home/alastair/verovio/src/doc.cpp",
    line=1836, function=<optimised out>) at assert.c:92
#6  0x00007ffff7aa6e26 in __GI___assert_fail (assertion=0x555555e44218 "m_currentScore",
    file=0x555555e437b8 "/home/alastair/verovio/src/doc.cpp", line=1836,
    function=0x555555e441f0 "vrv::Score* vrv::Doc::GetCurrentScore()") at assert.c:101
#7  0x00005555556cc6c6 in vrv::Doc::GetCurrentScore (this=0x7fffffffd778)
    at /home/alastair/verovio/src/doc.cpp:1836
#8  0x00005555556cc700 in vrv::Doc::GetCurrentScoreDef (this=0x7fffffffd778)
    at /home/alastair/verovio/src/doc.cpp:1843
#9  0x00005555556c2f2e in vrv::Doc::GenerateDocumentScoreDef (this=0x7fffffffd778)
    at /home/alastair/verovio/src/doc.cpp:167
#10 0x0000555555860c85 in vrv::MEIInput::ReadDoc (this=0x5555561340c0, root=...)
    at /home/alastair/verovio/src/iomei.cpp:3139
#11 0x000055555585f0d5 in vrv::MEIInput::Import (this=0x5555561340c0,
    mei="<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<?xml-model href=\"http://www.aruspix.net/mei-page-based-2013-11-05.rng\" type=\"application/xml\" schematypens=\"http://relaxng.org/ns/structure/1.0\"?>\n<mei xmlns=\""...) at /home/alastair/verovio/src/iomei.cpp:2568
#12 0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd770,
    data="<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<?xml-model href=\"http://www.aruspix.net/mei-page-based-2013-11-05.rng\" type=\"application/xml
--Type <RET> for more, q to quit, c to continue without paging--
=\""...) at /home/alastair/verovio/src/toolkit.cpp:658
#13 0x0000555555a2cfde in vrv::Toolkit::LoadFile (this=0x7fffffffd770, filename="../GB-Lbl_A103b_025_0.mei")
    at /home/alastair/verovio/src/toolkit.cpp:290
#14 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe1e8) at /home/alastair/verovio/tools/main.cpp:454
(gdb)
```

**Comment by alastair** [comment]
@lpugin yes, it works on this file, thanks! I'll test it on some others from our collection too
