### ISSUE TITLE
Crashes when converting some musicxml files

### ISSUE THREAD

**Issue by alastair** [rism-digital/verovio#2428]
**Describe the problem**
As part of our work in the Trompa project, I processed a large number of MusicXML files from CPDL, converting them to MEI/SVG with verovio. We found that about 10% of the files caused verovio to crash while performing the conversion. We were able to work around this in most cases by opening and re-saving musicxml using musescore, and then using verovio on the new files.

This is a companion issue to #2427, however the crashes are in different places. In order to reduce the number of issues I won't add one for each crash location, but in the list below I have grouped them by cause - there are a few files that crash in the same place.

I did a spot check of these files - verovio doesn't output any errors, and musescore doesn't say that the files are invalid either.

**To Reproduce**

I've included a list at the of the mxl files that crash with this specific error, along with a gdb stacktrace with debugging symbols for each of them

run `./verovio -r ../data/ -o output.svg [inputfile.mxl]`

**Expected behavior**
Verovio successfully converts the file, or raises an error and exits cleanly

**Input data**
See links below

**Verovio information**
 - Version of Verovio: git `develop`
 - Binding: command line

**Environment information (as appropriate)**
 - OS: linux

**Additional context**

### in `vrv::MusicXmlInput::ReadMusicXmlBarLine`

[La cortesia (Orlando di Lasso) - ChoralWiki](https://cpdl.org/wiki/index.php/La_cortesia_(Orlando_di_Lasso))
 * MusicXML: https://www.cpdl.org/wiki/images/8/83/Orlando_de_Lassus_La_cortesia.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ed5145 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#0  0x00007ffff7ed5145 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff7ed552e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000055555588e949 in vrv::MusicXmlInput::ReadMusicXmlBarLine (this=0x55555614a910, node=..., measure=0x5555562c1ee0, measureNum="8") at /home/alastair/verovio/src/iomusxml.cpp:1760
#3  0x000055555588c5d9 in vrv::MusicXmlInput::ReadMusicXmlMeasure (this=0x55555614a910, node=..., section=0x55555615ca20, measure=0x5555562c1ee0, nbStaves=1, staffOffset=0, index=7) at /home/alastair/verovio/src/iomusxml.cpp:1535
#4  0x000055555588b5e1 in vrv::MusicXmlInput::ReadMusicXmlPart (this=0x55555614a910, node=..., section=0x55555615ca20, nbStaves=1, staffOffset=0) at /home/alastair/verovio/src/iomusxml.cpp:1417
#5  0x0000555555886c0e in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a910, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1008
#6  0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a910, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 1.0 Partwise//EN\" \"http://www.musicxml.org/dtds/1.0/partwise.dtd\">\r\n<score-partwise>"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#7  0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5d0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 1.0 Partwise//EN\" \"http://www.musicxml.org/dtds/1.0/partwise.dtd\">\r\n<score-partwise>"...) at /home/alastair/verovio/src/toolkit.cpp:658
#8  0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5d0, bytes=std::vector of length 8715, capacity 8716 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#9  0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5d0, filename="/tmp/tmpal6vqrue/Orlando_de_Lassus_La_cortesia.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#10 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5d0, filename="/tmp/tmpal6vqrue/Orlando_de_Lassus_La_cortesia.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#11 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe048) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

---

[Ancor che col partire (Cipriano de Rore) - ChoralWiki](https://cpdl.org/wiki/index.php/Ancor_che_col_partire_(Cipriano_de_Rore))
 * MusicXML: https://www.cpdl.org/wiki/images/5/5e/De_Rore-Anchor_chi_col_partire.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ed5145 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#0  0x00007ffff7ed5145 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff7ed552e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000055555588e949 in vrv::MusicXmlInput::ReadMusicXmlBarLine (this=0x55555614a910, node=..., measure=0x5555563d99c0, measureNum="60") at /home/alastair/verovio/src/iomusxml.cpp:1760
#3  0x000055555588c5d9 in vrv::MusicXmlInput::ReadMusicXmlMeasure (this=0x55555614a910, node=..., section=0x5555561ab1b0, measure=0x5555563d99c0, nbStaves=1, staffOffset=0, index=59) at /home/alastair/verovio/src/iomusxml.cpp:1535
#4  0x000055555588b5e1 in vrv::MusicXmlInput::ReadMusicXmlPart (this=0x55555614a910, node=..., section=0x5555561ab1b0, nbStaves=1, staffOffset=0) at /home/alastair/verovio/src/iomusxml.cpp:1417
#5  0x0000555555886c0e in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a910, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1008
#6  0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a910, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\r\n<score-partwise vers"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#7  0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5d0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 3.1 Partwise//EN\" \"http://www.musicxml.org/dtds/partwise.dtd\">\r\n<score-partwise vers"...) at /home/alastair/verovio/src/toolkit.cpp:658
#8  0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5d0, bytes=std::vector of length 13865, capacity 13866 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#9  0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5d0, filename="/tmp/tmpjeustgca/De_Rore-Anchor_chi_col_partire.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#10 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5d0, filename="/tmp/tmpjeustgca/De_Rore-Anchor_chi_col_partire.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#11 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe048) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

---

[O belle fusa (Orlando di Lasso) - ChoralWiki](https://cpdl.org/wiki/index.php/O_belle_fusa_(Orlando_di_Lasso))
 * MusicXML: https://www.cpdl.org/wiki/images/2/24/Lasso-O_belle_fusa_SATB.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ed5145 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#0  0x00007ffff7ed5145 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff7ed552e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x000055555588e949 in vrv::MusicXmlInput::ReadMusicXmlBarLine (this=0x55555614a910, node=..., measure=0x555556417390, measureNum="48") at /home/alastair/verovio/src/iomusxml.cpp:1760
#3  0x000055555588c5d9 in vrv::MusicXmlInput::ReadMusicXmlMeasure (this=0x55555614a910, node=..., section=0x55555615c9c0, measure=0x555556417390, nbStaves=1, staffOffset=0, index=47) at /home/alastair/verovio/src/iomusxml.cpp:1535
#4  0x000055555588b5e1 in vrv::MusicXmlInput::ReadMusicXmlPart (this=0x55555614a910, node=..., section=0x55555615c9c0, nbStaves=1, staffOffset=0) at /home/alastair/verovio/src/iomusxml.cpp:1417
#5  0x0000555555886c0e in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a910, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1008
#6  0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a910, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 1.0 Partwise//EN\" \"http://www.musicxml.org/dtds/1.0/partwise.dtd\">\r\n<score-partwise>"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#7  0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5e0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD MusicXML 1.0 Partwise//EN\" \"http://www.musicxml.org/dtds/1.0/partwise.dtd\">\r\n<score-partwise>"...) at /home/alastair/verovio/src/toolkit.cpp:658
#8  0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5e0, bytes=std::vector of length 10655, capacity 10656 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#9  0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5e0, filename="/tmp/tmpmao0873g/Lasso-O_belle_fusa_SATB.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#10 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5e0, filename="/tmp/tmpmao0873g/Lasso-O_belle_fusa_SATB.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#11 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe058) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

---

###  in`vrv::MusicXmlInput::AddClefs`

[Benedictus es Domine (Orlando di Lasso) - ChoralWiki](https://cpdl.org/wiki/index.php/Benedictus_es_Domine_(Orlando_di_Lasso))
 * MusicXML: https://www.cpdl.org/wiki/images/1/16/Lassus_Benedictus.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555568444c in __gnu_cxx::__normal_iterator<vrv::Object**, std::vector<vrv::Object*, std::allocator<vrv::Object*> > >::__normal_iterator (this=0x7fffffffa760, __i=<error reading variable>) at /usr/include/c++/11/bits/stl_iterator.h:1011
1011	      : _M_current(__i) { }
#0  0x000055555568444c in __gnu_cxx::__normal_iterator<vrv::Object**, std::vector<vrv::Object*, std::allocator<vrv::Object*> > >::__normal_iterator (this=0x7fffffffa760, __i=<error reading variable>) at /usr/include/c++/11/bits/stl_iterator.h:1011
#1  0x000055555568457c in std::vector<vrv::Object*, std::allocator<vrv::Object*> >::begin (this=0x50) at /usr/include/c++/11/bits/stl_vector.h:812
#2  0x0000555555967697 in vrv::Object::GetChildIndex (this=0x0, child=0x555556419090) at /home/alastair/verovio/src/object.cpp:692
#3  0x000055555587fabb in vrv::MusicXmlInput::AddClefs (this=0x55555614a900, measure=0x0, clefChange=...) at /home/alastair/verovio/src/iomusxml.cpp:229
#4  0x000055555587f7ad in vrv::MusicXmlInput::ProcessClefChangeQueue (this=0x55555614a900, section=0x55555615ca40) at /home/alastair/verovio/src/iomusxml.cpp:197
#5  0x0000555555886cd3 in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a900, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1018
#6  0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a900, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#7  0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5e0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/toolkit.cpp:658
#8  0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5e0, bytes=std::vector of length 7791, capacity 7792 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#9  0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5e0, filename="/tmp/tmp5zulp1q4/Lassus_Benedictus.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#10 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5e0, filename="/tmp/tmp5zulp1q4/Lassus_Benedictus.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#11 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe058) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

---

[Non è ch'il duol mi scemi (Cipriano de Rore) - ChoralWiki](https://cpdl.org/wiki/index.php/Non_è_ch'il_duol_mi_scemi_(Cipriano_de_Rore))
 * MusicXML: https://www.cpdl.org/wiki/images/0/00/DeRore_Non-e-chil-duol.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555568444c in __gnu_cxx::__normal_iterator<vrv::Object**, std::vector<vrv::Object*, std::allocator<vrv::Object*> > >::__normal_iterator (this=0x7fffffffa760, __i=<error reading variable>) at /usr/include/c++/11/bits/stl_iterator.h:1011
1011	      : _M_current(__i) { }
#0  0x000055555568444c in __gnu_cxx::__normal_iterator<vrv::Object**, std::vector<vrv::Object*, std::allocator<vrv::Object*> > >::__normal_iterator (this=0x7fffffffa760, __i=<error reading variable>) at /usr/include/c++/11/bits/stl_iterator.h:1011
#1  0x000055555568457c in std::vector<vrv::Object*, std::allocator<vrv::Object*> >::begin (this=0x50) at /usr/include/c++/11/bits/stl_vector.h:812
#2  0x0000555555967697 in vrv::Object::GetChildIndex (this=0x0, child=0x55555659f5a0) at /home/alastair/verovio/src/object.cpp:692
#3  0x000055555587fabb in vrv::MusicXmlInput::AddClefs (this=0x55555614a910, measure=0x0, clefChange=...) at /home/alastair/verovio/src/iomusxml.cpp:229
#4  0x000055555587f7ad in vrv::MusicXmlInput::ProcessClefChangeQueue (this=0x55555614a910, section=0x55555615c9b0) at /home/alastair/verovio/src/iomusxml.cpp:197
#5  0x0000555555886cd3 in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a910, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1018
#6  0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a910, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#7  0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5e0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/toolkit.cpp:658
#8  0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5e0, bytes=std::vector of length 11042, capacity 11043 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#9  0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5e0, filename="/tmp/tmp1szaa95a/DeRore_Non-e-chil-duol.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#10 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5e0, filename="/tmp/tmp1szaa95a/DeRore_Non-e-chil-duol.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#11 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe058) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

---

[Vezzosi augelli (Luca Marenzio) - ChoralWiki](https://cpdl.org/wiki/index.php/Vezzosi_augelli_(Luca_Marenzio))
 * MusicXML: https://www.cpdl.org/wiki/images/3/32/Marenzio_Vezzosi.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555568444c in __gnu_cxx::__normal_iterator<vrv::Object**, std::vector<vrv::Object*, std::allocator<vrv::Object*> > >::__normal_iterator (this=0x7fffffffa760, __i=<error reading variable>) at /usr/include/c++/11/bits/stl_iterator.h:1011
1011	      : _M_current(__i) { }
#0  0x000055555568444c in __gnu_cxx::__normal_iterator<vrv::Object**, std::vector<vrv::Object*, std::allocator<vrv::Object*> > >::__normal_iterator (this=0x7fffffffa760, __i=<error reading variable>) at /usr/include/c++/11/bits/stl_iterator.h:1011
#1  0x000055555568457c in std::vector<vrv::Object*, std::allocator<vrv::Object*> >::begin (this=0x50) at /usr/include/c++/11/bits/stl_vector.h:812
#2  0x0000555555967697 in vrv::Object::GetChildIndex (this=0x0, child=0x55555664f710) at /home/alastair/verovio/src/object.cpp:692
#3  0x000055555587fabb in vrv::MusicXmlInput::AddClefs (this=0x55555614a900, measure=0x0, clefChange=...) at /home/alastair/verovio/src/iomusxml.cpp:229
#4  0x000055555587f7ad in vrv::MusicXmlInput::ProcessClefChangeQueue (this=0x55555614a900, section=0x55555615cb50) at /home/alastair/verovio/src/iomusxml.cpp:197
#5  0x0000555555886cd3 in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a900, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1018
#6  0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a900, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#7  0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5e0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/toolkit.cpp:658
#8  0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5e0, bytes=std::vector of length 11525, capacity 11526 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#9  0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5e0, filename="/tmp/tmp_n6ukhf6/Marenzio_Vezzosi.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#10 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5e0, filename="/tmp/tmp_n6ukhf6/Marenzio_Vezzosi.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#11 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe058) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

---

### crashes in other places

[In monte Oliveti (Giovanni Pierluigi da Palestrina) - ChoralWiki](https://cpdl.org/wiki/index.php/In_monte_Oliveti_(Giovanni_Pierluigi_da_Palestrina))
 * MusicXML: https://www.cpdl.org/wiki/images/5/5a/In_monte_Oliveti_Palestrina.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000555555670530 in vrv::Object::GetParent (this=0xbff0000000000000) at /home/alastair/verovio/cmake/../include/vrv/object.h:295
295	    Object *GetParent() const { return m_parent; }
#0  0x0000555555670530 in vrv::Object::GetParent (this=0xbff0000000000000) at /home/alastair/verovio/cmake/../include/vrv/object.h:295
#1  0x000055555596570e in vrv::Object::ClearChildren (this=0x5555567fcfe8) at /home/alastair/verovio/src/object.cpp:352
#2  0x000055555596499e in vrv::Object::~Object (this=0x5555567fcfe8, __in_chrg=<optimised out>) at /home/alastair/verovio/src/object.cpp:180
#3  0x0000555555743560 in vrv::HorizontalAligner::~HorizontalAligner (this=0x5555567fcfe8, __in_chrg=<optimised out>) at /home/alastair/verovio/src/horizontalaligner.cpp:44
#4  0x000055555574387a in vrv::MeasureAligner::~MeasureAligner (this=0x5555567fcfe8, __in_chrg=<optimised out>) at /home/alastair/verovio/src/horizontalaligner.cpp:106
#5  0x0000555555931fc4 in vrv::Measure::~Measure (this=0x5555567fcd60, __in_chrg=<optimised out>) at /home/alastair/verovio/src/measure.cpp:90
#6  0x00005555559320bc in vrv::Measure::~Measure (this=0x5555567fcd60, __in_chrg=<optimised out>) at /home/alastair/verovio/src/measure.cpp:90
#7  0x0000555555880797 in vrv::MusicXmlInput::AddMeasure (this=0x55555614a910, section=0x55555615c770, measure=0x5555567fcd60, i=75) at /home/alastair/verovio/src/iomusxml.cpp:362
#8  0x000055555588b605 in vrv::MusicXmlInput::ReadMusicXmlPart (this=0x55555614a910, node=..., section=0x55555615c770, nbStaves=1, staffOffset=3) at /home/alastair/verovio/src/iomusxml.cpp:1419
#9  0x0000555555886c0e in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a910, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1008
#10 0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a910, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.5-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#11 0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5e0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.5-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/toolkit.cpp:658
#12 0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5e0, bytes=std::vector of length 12494, capacity 12495 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#13 0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5e0, filename="/tmp/tmp8aaoxajp/In_monte_Oliveti_Palestrina.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#14 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5e0, filename="/tmp/tmp8aaoxajp/In_monte_Oliveti_Palestrina.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#15 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe058) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

---

[Nunc dimittis (Tomás Luis de Victoria) - ChoralWiki](https://cpdl.org/wiki/index.php/Nunc_dimittis_(Tomás_Luis_de_Victoria))
 * MusicXML: https://www.cpdl.org/wiki/images/e/eb/Nunc_dimittis_Canticum_Simeonis.mxl
<details>
<summary>stacktrace</summary>

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348269184) at pthread_kill.c:44
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348269184) at pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737348269184) at pthread_kill.c:80
#2  __GI___pthread_kill (threadid=140737348269184, signo=signo@entry=6) at pthread_kill.c:91
#3  0x00007ffff7aae476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7a947b7 in __GI_abort () at abort.c:79
#5  0x00007ffff7a946db in __assert_fail_base (fmt=0x7ffff7c48770 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555555e57da6 "staff", file=0x555555e57be8 "/home/alastair/verovio/src/iomusxml.cpp", line=1635, function=<optimised out>) at assert.c:92
#6  0x00007ffff7aa5e26 in __GI___assert_fail (assertion=0x555555e57da6 "staff", file=0x555555e57be8 "/home/alastair/verovio/src/iomusxml.cpp", line=1635, function=0x555555e58dc8 "void vrv::MusicXmlInput::ReadMusicXmlAttributes(pugi::xml_node, vrv::Section*, vrv::Measure*, const string&)") at assert.c:101
#7  0x000055555588d5bb in vrv::MusicXmlInput::ReadMusicXmlAttributes (this=0x55555614a910, node=..., section=0x55555615ca20, measure=0x55555668e470, measureNum="3") at /home/alastair/verovio/src/iomusxml.cpp:1635
#8  0x000055555588c499 in vrv::MusicXmlInput::ReadMusicXmlMeasure (this=0x55555614a910, node=..., section=0x55555615ca20, measure=0x55555668e470, nbStaves=1, staffOffset=5, index=2) at /home/alastair/verovio/src/iomusxml.cpp:1529
#9  0x000055555588b5e1 in vrv::MusicXmlInput::ReadMusicXmlPart (this=0x55555614a910, node=..., section=0x55555615ca20, nbStaves=1, staffOffset=5) at /home/alastair/verovio/src/iomusxml.cpp:1417
#10 0x0000555555886c0e in vrv::MusicXmlInput::ReadMusicXml (this=0x55555614a910, root=...) at /home/alastair/verovio/src/iomusxml.cpp:1008
#11 0x000055555587f043 in vrv::MusicXmlInput::Import (this=0x55555614a910, musicxml="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/iomusxml.cpp:119
#12 0x0000555555a2f028 in vrv::Toolkit::LoadData (this=0x7fffffffd5d0, data="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<!--MusicXML 2.0 file created by CapToMusic.py CapXML to MusicXML converter version 2.4-->\n<!DOCTYPE score-partwise PUBLIC \"-//Recordare//DTD Mus"...) at /home/alastair/verovio/src/toolkit.cpp:658
#13 0x0000555555a2daa5 in vrv::Toolkit::LoadZipData (this=0x7fffffffd5d0, bytes=std::vector of length 8040, capacity 8041 = {...}) at /home/alastair/verovio/src/toolkit.cpp:405
#14 0x0000555555a2d75f in vrv::Toolkit::LoadZipFile (this=0x7fffffffd5d0, filename="/tmp/tmp1zmip2ye/Nunc_dimittis_Canticum_Simeonis.mxl") at /home/alastair/verovio/src/toolkit.cpp:380
#15 0x0000555555a2ce6e in vrv::Toolkit::LoadFile (this=0x7fffffffd5d0, filename="/tmp/tmp1zmip2ye/Nunc_dimittis_Canticum_Simeonis.mxl") at /home/alastair/verovio/src/toolkit.cpp:271
#16 0x000055555562ca4d in main (argc=6, argv=0x7fffffffe048) at /home/alastair/verovio/tools/main.cpp:454
```

</details>

**Comment by rettinghaus** [comment]
The "crashes in other places" are the same "polymeter problems" as in #2427.
